# site settings
title: RoboKoding
subtitle: The basics of programming and robotics.
email: letstalk@robokoding.com
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
legal: RoboKoding LTD
author:
street_address: Kesa tee 5-1
city: Pärnumaa
state: Tori vald
zip_code: 85009
country: Estonia
phone: (+372) 55600515

# menu/nav pages
nav-pages: ["Workshops", "Courses", "Remote Labs", "Kits", "Consulting", "Training", "About Us"]

# homepage tiles
tiles-pages: ["Workshops", "Courses", "Remote Labs", "Kits", "Consulting", "Training"] # which pages to show
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 2

# social settings
500px_url:
facebook_url: https://www.facebook.com/robokoding
github_url: https://github.com/robokoding
gitlab_url:
googleplus_url:
instagram_url: https://www.instagram.com/robokoding
linkedin_url: https://www.linkedin.com/company/robokoding
pinterest_url:
slack_url:
twitter_url: https://twitter.com/robokoding

# build settings
markdown: kramdown

sass:
  style: compressed

include: ["_pages"]
permalink: /:title/
